"""Kullanıcı isteği (2026-08-13): KAP'ın kendi Sektörler sayfasından canlı
kazınan ince sektör etiketi bazen eksik/hatalı çıkıyordu (örn. "Enerji
Üretim ve Dağıtım" gibi tek bir KAP kovasına birbiriyle alakasız iş
modelleri düşüyordu) -- kullanıcı Fintables'ın sektörler sayfasından
(fintables.com/sektorler) TÜM BİST evrenini (648 hisse, 44 sektör) elle
doğrulayıp `bist-sektorler-ve-hisseler.md` dosyasına aktardı ve bunun
YENİ, daha DOĞRU/EKSİKSİZ ince sektör kaynağı olmasını istedi.

Bu modül `src/fetchers/kap.py::KAP_SEKTOR_TO_UST_SEKTOR`/`ust_sektor_for_kap`/
`sirket_turu_on_tahmin_from_kap` İLE AYNI DESENİ (statik sözlük + saf
fonksiyon, Kural 3: eşleşme yoksa None döner, uydurma YAPILMAZ) izler --
KAP'ın canlı-kazınan kaynağının YERİNE (bkz. refresh_universe.py::_refresh_bist),
KAP fonksiyonları KOD TABANINDAN SİLİNMEZ (persona kural 8: genişlet ama
çöpe atma) -- ileride yeni/henüz Fintables'a düşmemiş bir IPO için YEDEK
kaynak olarak kalabilir.

`FINTABLES_TICKER_TO_SEKTOR` `scripts/parse_fintables_sektor.py` ile
`bist-sektorler-ve-hisseler.md`'den TEK SEFERLİK üretildi (13 Ağustos 2026
itibarıyla, 637 hisse -- dosyanın kendi "Sektörü Tanımsız (11)" bölümündeki
hisseler BİLEREK bu sözlükte YOK, Kural 3: Fintables'ın KENDİSİ de bu 11
hisseyi sınıflandıramamış, uydurma yapılmaz).
"""

from __future__ import annotations

# --- 44 Fintables ince sektörü -> 11 ortak üst-sektör (GICS-sadeleştirilmiş,
# kap.py::KAP_SEKTOR_TO_UST_SEKTOR İLE AYNI 11 değer seti) -----------------
# Kural: GICS'in "Materials" karşılığı bu projede "Ana Metaller ve
# Madencilik" (metal DIŞI ama malzeme-ağırlıklı sektörler de -- kağıt,
# ambalaj, cam/seramik, kimya, taş/toprak/çimento -- BURAYA düşer, kap.py'nin
# KENDİ "KAĞIT VE KAĞIT ÜRÜNLERİ BASIM"/"TAŞ VE TOPRAĞA DAYALI" -> "Ana
# Metaller ve Madencilik" eşlemesiyle TUTARLI). Otomotiv + Otomotiv Yan
# Sanayi GICS "Consumer Discretionary" (Tüketici Döngüsel) standardına göre
# ikisi de aynı üst-sektörde.
FINTABLES_SEKTOR_TO_UST_SEKTOR: dict[str, str] = {
    "Ambalaj": "Ana Metaller ve Madencilik",
    "Ana Metal": "Ana Metaller ve Madencilik",
    "Aracı Kurum": "Finans",
    "Bankacılık": "Finans",
    "Bilişim ve Yazılım": "Teknoloji",
    "Cam, Seramik, Porselen": "Ana Metaller ve Madencilik",
    "Dayanıklı Tüketim Ürünleri": "Tüketici (Döngüsel)",
    "Destek ve Hizmet": "Sanayi",
    "Emeklilik": "Finans",
    "Enerji Teknolojileri": "Sanayi",  # ekipman/teknoloji ÜRETİCİLERİ (solar panel, enerji ekipmanı) -- fiili enerji ÜRETİCİSİ DEĞİL
    "Enerji Üretim ve Dağıtım": "Kamu Hizmetleri",  # elektrik/doğalgaz üretim-dağıtım -- kap.py "ELEKTRİK GAZ VE BUHAR" ile AYNI kova
    "Faktoring": "Finans",
    "Finansal Kiralama": "Finans",
    "Gayrimenkul": "Gayrimenkul/GYO",
    "Girişim Sermayesi Yat. Ort.": "Finans",
    "Giyim, Tekstil ve Deri Ürünleri Perakendeciliği": "Tüketici (Döngüsel)",
    "Gıda Perakendeciliği": "Tüketici (Temel)",
    "Gıda ve İçecek": "Tüketici (Temel)",
    "Haberleşme": "İletişim",
    "Holding": "Finans",
    "İlaç ve Sağlık": "Sağlık",
    "İmalat": "Sanayi",
    "İnşaat": "Sanayi",
    "Kağıt ve Kağıt Ürünleri": "Ana Metaller ve Madencilik",
    "Kimya ve Plastik": "Ana Metaller ve Madencilik",
    "Madencilik ve Taş Ocakçılığı": "Ana Metaller ve Madencilik",
    "Menkul Kıymet Yat. Ort.": "Finans",
    "Metal Eşya ve Makine": "Sanayi",
    "Mobilya ve Dekorasyon": "Tüketici (Döngüsel)",
    "Otomotiv": "Tüketici (Döngüsel)",
    "Otomotiv Yan Sanayi": "Tüketici (Döngüsel)",
    "Savunma": "Sanayi",
    "Servis Taşımacılığı ve Araç Kiralama": "Sanayi",
    "Sigorta": "Finans",
    "Spor": "Tüketici (Döngüsel)",
    "Tarım, Hayvancılık, Balıkçılık": "Tüketici (Temel)",
    "Tasarruf Finansman": "Finans",
    "Taş, Toprak, Çimento": "Ana Metaller ve Madencilik",
    "Teknolojik Ürün Ticareti": "Teknoloji",
    "Tekstil, Giyim ve Deri": "Tüketici (Döngüsel)",
    "Toptan ve Perakende Ticaret": "Tüketici (Döngüsel)",
    "Turizm": "Tüketici (Döngüsel)",
    "Ulaştırma": "Sanayi",
    "Varlık Yönetimi": "Finans",
}

# Sadece KAP ince sektöründe zaten ayrık/kesin olan 2 kategori (bkz.
# kap.py::_KAP_FINE_SECTOR_TO_SIRKET_TURU_KESIN İLE AYNI ilke) -- "Gayrimenkul"
# BİLEREK burada YOK (Fintables bu kovada hem GYO'ları hem genel gayrimenkul
# şirketlerini karıştırıyor, kesin ayrım SADECE financial_group ile
# yapılabilir, Kural 3: uydurma yapılmaz).
_FINTABLES_SEKTOR_TO_SIRKET_TURU_KESIN: dict[str, str] = {
    "Bankacılık": "banka",
    "Sigorta": "sigorta",
}

_SIRKET_TURU_ONTAHMIN_DISI_UST_SEKTORLER = frozenset({"Finans", "Gayrimenkul/GYO"})

# Ticker-düzeyi override -- kap.py::KAP_TICKER_SECTOR_OVERRIDES İLE AYNI
# desen. SADECE TUPRS kaldı: Fintables onu da "Kimya ve Plastik" kovasına
# koymuş ama gerçek iş modeli rafineri (Enerji). kap.py'deki TAVHL/DEVA/
# GENKM/SANFM/ONCSM/MEDTR override'ları BİLEREK buraya TAŞINMADI --
# Fintables'ın KENDİSİ TAVHL'i zaten doğru kovaya (Ulaştırma) koymuş, DEVA/
# ONCSM/MEDTR zaten "İlaç ve Sağlık"ta; GENKM/SANFM için Fintables'ın
# gösterdiği UNVAN (Gentaş Kimya / Sanifoam Endüstri) eski override
# yorumundaki varsayılan şirket kimliğiyle (Gen İlaç / Sanifarma) ÖRTÜŞMÜYOR
# -- bu ÇELİŞKİ kullanıcıya AÇIKÇA bildirildi, kod BİLEREK Fintables'ın
# GÜNCEL/doğrulanmış sınıflandırmasına güvenir (Kural 3: eski, doğrulanamayan
# bir varsayımı ISRARLA korumak yerine).
FINTABLES_TICKER_OVERRIDES: dict[str, str] = {
    "TUPRS": "Enerji",
}


def ust_sektor_for_fintables(ticker: str, fine_sector: str) -> str | None:
    """`kap.ust_sektor_for_kap()` İLE BİREBİR AYNI kural sırası: ticker
    override varsa o kullanılır, yoksa `FINTABLES_SEKTOR_TO_UST_SEKTOR`
    denenir, ikisi de yoksa None (Kural 3)."""
    override = FINTABLES_TICKER_OVERRIDES.get(ticker.strip().upper())
    if override is not None:
        return override
    return FINTABLES_SEKTOR_TO_UST_SEKTOR.get(fine_sector)


def sirket_turu_on_tahmin_from_fintables(fine_sector: str) -> str | None:
    """`kap.sirket_turu_on_tahmin_from_kap()` İLE BİREBİR AYNI mantık --
    ön-tahmindir, `financial_group` dolduğunda pipeline KESİN değerle
    ÜZERİNE YAZAR (bu fonksiyon o adımı YAPMAZ)."""
    kesin = _FINTABLES_SEKTOR_TO_SIRKET_TURU_KESIN.get(fine_sector)
    if kesin is not None:
        return kesin
    ust_sektor = FINTABLES_SEKTOR_TO_UST_SEKTOR.get(fine_sector)
    if ust_sektor is None:
        return None
    if ust_sektor in _SIRKET_TURU_ONTAHMIN_DISI_UST_SEKTORLER:
        return None
    return "sanayi"


# --- Ticker -> Fintables ince sektör (648 hisse, 13 Ağustos 2026) ---------
FINTABLES_TICKER_TO_SEKTOR: dict[str, str] = {
    "A1CAP": "Aracı Kurum",
    "A1YEN": "Enerji Üretim ve Dağıtım",
    "AAGYO": "Gayrimenkul",
    "ACSEL": "Kimya ve Plastik",
    "ADEL": "İmalat",
    "ADESE": "Gayrimenkul",
    "ADGYO": "Gayrimenkul",
    "AEFES": "Gıda ve İçecek",
    "AFYON": "Taş, Toprak, Çimento",
    "AGESA": "Emeklilik",
    "AGHOL": "Holding",
    "AGROT": "Gıda ve İçecek",
    "AGYO": "Gayrimenkul",
    "AHGAZ": "Enerji Üretim ve Dağıtım",
    "AHSGY": "Gayrimenkul",
    "AKBNK": "Bankacılık",
    "AKCNS": "Taş, Toprak, Çimento",
    "AKENR": "Enerji Üretim ve Dağıtım",
    "AKFGY": "Gayrimenkul",
    "AKFIS": "İnşaat",
    "AKFYE": "Enerji Üretim ve Dağıtım",
    "AKGRT": "Sigorta",
    "AKHAN": "Gıda ve İçecek",
    "AKMGY": "Gayrimenkul",
    "AKSA": "Kimya ve Plastik",
    "AKSEN": "Enerji Üretim ve Dağıtım",
    "AKSGY": "Gayrimenkul",
    "AKSUE": "Enerji Üretim ve Dağıtım",
    "AKYHO": "Destek ve Hizmet",
    "ALARK": "Holding",
    "ALBRK": "Bankacılık",
    "ALBTN": "Taş, Toprak, Çimento",
    "ALCAR": "Dayanıklı Tüketim Ürünleri",
    "ALCTL": "Haberleşme",
    "ALFAS": "Enerji Teknolojileri",
    "ALGYO": "Gayrimenkul",
    "ALKA": "Kağıt ve Kağıt Ürünleri",
    "ALKIM": "Kimya ve Plastik",
    "ALKLC": "Gıda ve İçecek",
    "ALTNY": "Savunma",
    "ALVES": "İmalat",
    "ANELE": "İnşaat",
    "ANGEN": "İlaç ve Sağlık",
    "ANHYT": "Emeklilik",
    "ANSGR": "Sigorta",
    "ARASE": "Enerji Üretim ve Dağıtım",
    "ARCLK": "Dayanıklı Tüketim Ürünleri",
    "ARDYZ": "Bilişim ve Yazılım",
    "ARENA": "Teknolojik Ürün Ticareti",
    "ARFYE": "Enerji Üretim ve Dağıtım",
    "ARMGD": "Gıda ve İçecek",
    "ARSAN": "Tekstil, Giyim ve Deri",
    "ARTMS": "Tekstil, Giyim ve Deri",
    "ARZUM": "Dayanıklı Tüketim Ürünleri",
    "ASELS": "Savunma",
    "ASGYO": "Gayrimenkul",
    "ASTOR": "Enerji Teknolojileri",
    "ASUZU": "Otomotiv",
    "ATAGY": "Gayrimenkul",
    "ATAKP": "Gıda ve İçecek",
    "ATATP": "Bilişim ve Yazılım",
    "ATATR": "Turizm",
    "ATEKS": "Tekstil, Giyim ve Deri",
    "ATLAS": "Menkul Kıymet Yat. Ort.",
    "ATSYH": "Holding",
    "AVGYO": "Gayrimenkul",
    "AVHOL": "Holding",
    "AVOD": "Gıda ve İçecek",
    "AVPGY": "Gayrimenkul",
    "AVTUR": "Toptan ve Perakende Ticaret",
    "AYCES": "Turizm",
    "AYDEM": "Enerji Üretim ve Dağıtım",
    "AYEN": "Enerji Üretim ve Dağıtım",
    "AYES": "İmalat",
    "AYGAZ": "Kimya ve Plastik",
    "AZTEK": "Teknolojik Ürün Ticareti",
    "BAGFS": "Kimya ve Plastik",
    "BAHKM": "Kimya ve Plastik",
    "BAKAB": "Ambalaj",
    "BALAT": "Otomotiv Yan Sanayi",
    "BALSU": "Gıda ve İçecek",
    "BANVT": "Gıda ve İçecek",
    "BARMA": "Ambalaj",
    "BASCM": "Taş, Toprak, Çimento",
    "BASGZ": "Enerji Üretim ve Dağıtım",
    "BAYRK": "Tekstil, Giyim ve Deri",
    "BEGYO": "Gayrimenkul",
    "BERA": "Holding",
    "BESLR": "Gıda ve İçecek",
    "BESTE": "Enerji Üretim ve Dağıtım",
    "BETAE": "Enerji Teknolojileri",
    "BEYAZ": "Destek ve Hizmet",
    "BFREN": "Otomotiv Yan Sanayi",
    "BIENY": "Cam, Seramik, Porselen",
    "BIGCH": "Gıda ve İçecek",
    "BIGEN": "Enerji Üretim ve Dağıtım",
    "BIGTK": "Destek ve Hizmet",
    "BIMAS": "Gıda Perakendeciliği",
    "BINBN": "Ulaştırma",
    "BINHO": "Holding",
    "BIOEN": "Enerji Üretim ve Dağıtım",
    "BIZIM": "Gıda Perakendeciliği",
    "BJKAS": "Spor",
    "BLCYT": "Holding",
    "BLUME": "Turizm",
    "BMSCH": "Ana Metal",
    "BMSTL": "Ana Metal",
    "BNTAS": "Ambalaj",
    "BOBET": "Taş, Toprak, Çimento",
    "BORLS": "Servis Taşımacılığı ve Araç Kiralama",
    "BORSK": "Gıda ve İçecek",
    "BOSSA": "Tekstil, Giyim ve Deri",
    "BRISA": "Otomotiv Yan Sanayi",
    "BRKO": "Tekstil, Giyim ve Deri",
    "BRKSN": "İnşaat",
    "BRKVY": "Varlık Yönetimi",
    "BRLSM": "Enerji Teknolojileri",
    "BRMEN": "Tekstil, Giyim ve Deri",
    "BRSAN": "Ana Metal",
    "BRYAT": "Holding",
    "BSOKE": "Taş, Toprak, Çimento",
    "BTCIM": "Taş, Toprak, Çimento",
    "BUCIM": "Taş, Toprak, Çimento",
    "BULGS": "Girişim Sermayesi Yat. Ort.",
    "BURCE": "Ana Metal",
    "BURVA": "Ana Metal",
    "BVSAN": "İmalat",
    "BYDNR": "Gıda ve İçecek",
    "CANTE": "Enerji Üretim ve Dağıtım",
    "CASA": "Kimya ve Plastik",
    "CATES": "Enerji Üretim ve Dağıtım",
    "CCOLA": "Gıda ve İçecek",
    "CELHA": "Ana Metal",
    "CEMAS": "Ana Metal",
    "CEMTS": "Ana Metal",
    "CEMZY": "Tarım, Hayvancılık, Balıkçılık",
    "CEOEM": "Destek ve Hizmet",
    "CGCAM": "Cam, Seramik, Porselen",
    "CIMSA": "Taş, Toprak, Çimento",
    "CITAS": "Gıda ve İçecek",
    "CLEBI": "Ulaştırma",
    "CMBTN": "Taş, Toprak, Çimento",
    "CMENT": "Taş, Toprak, Çimento",
    "CONSE": "Enerji Üretim ve Dağıtım",
    "COSMO": "Holding",
    "CRDFA": "Faktoring",
    "CRFSA": "Gıda Perakendeciliği",
    "CUSAN": "Ana Metal",
    "CVKMD": "Madencilik ve Taş Ocakçılığı",
    "CWENE": "Enerji Teknolojileri",
    "DAGHL": "Holding",
    "DAGI": "Tekstil, Giyim ve Deri",
    "DAPGM": "Gayrimenkul",
    "DARDL": "Gıda ve İçecek",
    "DCTTR": "Tarım, Hayvancılık, Balıkçılık",
    "DENGE": "Holding",
    "DERHL": "Tekstil, Giyim ve Deri",
    "DERIM": "Tekstil, Giyim ve Deri",
    "DESA": "Tekstil, Giyim ve Deri",
    "DESPC": "Teknolojik Ürün Ticareti",
    "DEVA": "İlaç ve Sağlık",
    "DGATE": "Teknolojik Ürün Ticareti",
    "DGGYO": "Gayrimenkul",
    "DGNMO": "Mobilya ve Dekorasyon",
    "DIRIT": "Tekstil, Giyim ve Deri",
    "DITAS": "Otomotiv Yan Sanayi",
    "DMRGD": "Gıda ve İçecek",
    "DMSAS": "Ana Metal",
    "DNISI": "Kimya ve Plastik",
    "DOAS": "Otomotiv",
    "DOBUR": "Kağıt ve Kağıt Ürünleri",
    "DOCO": "Destek ve Hizmet",
    "DOFER": "İmalat",
    "DOFRB": "İmalat",
    "DOGUB": "İmalat",
    "DOHOL": "Holding",
    "DOKTA": "Otomotiv Yan Sanayi",
    "DSTKF": "Faktoring",
    "DUNYH": "Gıda ve İçecek",
    "DURDO": "Ambalaj",
    "DURKN": "Gıda ve İçecek",
    "DYOBY": "Kimya ve Plastik",
    "DZGYO": "Gayrimenkul",
    "EBEBK": "Toptan ve Perakende Ticaret",
    "ECILC": "İlaç ve Sağlık",
    "ECOGR": "Enerji Üretim ve Dağıtım",
    "ECZYT": "Holding",
    "EDATA": "Bilişim ve Yazılım",
    "EDIP": "Gayrimenkul",
    "EFOR": "Gıda ve İçecek",
    "EFORC": "Gıda ve İçecek",
    "EGEEN": "Otomotiv Yan Sanayi",
    "EGEGY": "Gayrimenkul",
    "EGEPO": "İlaç ve Sağlık",
    "EGGUB": "Kimya ve Plastik",
    "EGPRO": "Kimya ve Plastik",
    "EGSER": "Cam, Seramik, Porselen",
    "EKDMR": "Ana Metal",
    "EKGYO": "Gayrimenkul",
    "EKIM": "Servis Taşımacılığı ve Araç Kiralama",
    "EKIZ": "Kimya ve Plastik",
    "EKOS": "Enerji Teknolojileri",
    "EKSUN": "Gıda ve İçecek",
    "ELITE": "Gıda ve İçecek",
    "EMKEL": "İmalat",
    "EMNIS": "Ambalaj",
    "EMPAE": "Toptan ve Perakende Ticaret",
    "ENDAE": "Enerji Üretim ve Dağıtım",
    "ENERY": "Enerji Üretim ve Dağıtım",
    "ENJSA": "Enerji Üretim ve Dağıtım",
    "ENKAI": "İnşaat",
    "ENSRI": "Tekstil, Giyim ve Deri",
    "ENTRA": "Enerji Üretim ve Dağıtım",
    "EPLAS": "Kimya ve Plastik",
    "ERBOS": "Ana Metal",
    "ERCB": "Ana Metal",
    "EREGL": "Ana Metal",
    "ERSU": "Gıda ve İçecek",
    "ESCAR": "Servis Taşımacılığı ve Araç Kiralama",
    "ESCOM": "Bilişim ve Yazılım",
    "ESEN": "Enerji Üretim ve Dağıtım",
    "ETILR": "Toptan ve Perakende Ticaret",
    "ETYAT": "Menkul Kıymet Yat. Ort.",
    "EUHOL": "Holding",
    "EUKYO": "Menkul Kıymet Yat. Ort.",
    "EUPWR": "Enerji Teknolojileri",
    "EUREN": "Enerji Üretim ve Dağıtım",
    "EUYO": "Menkul Kıymet Yat. Ort.",
    "EYGYO": "Gayrimenkul",
    "FADE": "Gıda ve İçecek",
    "FENER": "Spor",
    "FLAP": "Destek ve Hizmet",
    "FMIZP": "Otomotiv Yan Sanayi",
    "FONET": "Bilişim ve Yazılım",
    "FORMT": "Metal Eşya ve Makine",
    "FORTE": "Bilişim ve Yazılım",
    "FRIGO": "Gıda ve İçecek",
    "FRMPL": "Kimya ve Plastik",
    "FROTO": "Otomotiv",
    "FZLGY": "Gayrimenkul",
    "GARAN": "Bankacılık",
    "GARFA": "Faktoring",
    "GATEG": "Destek ve Hizmet",
    "GEDIK": "Aracı Kurum",
    "GEDZA": "Ambalaj",
    "GENIL": "İlaç ve Sağlık",
    "GENKM": "Kimya ve Plastik",
    "GENTS": "Mobilya ve Dekorasyon",
    "GEREL": "Metal Eşya ve Makine",
    "GESAN": "Enerji Teknolojileri",
    "GIPTA": "İmalat",
    "GLBMD": "Aracı Kurum",
    "GLCVY": "Varlık Yönetimi",
    "GLRMK": "İnşaat",
    "GLRYH": "Holding",
    "GLYHO": "Holding",
    "GMTAS": "Toptan ve Perakende Ticaret",
    "GOKNR": "Gıda ve İçecek",
    "GOLDA": "Gıda ve İçecek",
    "GOLTS": "Taş, Toprak, Çimento",
    "GOODY": "Otomotiv Yan Sanayi",
    "GOZDE": "Girişim Sermayesi Yat. Ort.",
    "GRNYO": "Menkul Kıymet Yat. Ort.",
    "GRSEL": "Servis Taşımacılığı ve Araç Kiralama",
    "GRTHO": "Gıda ve İçecek",
    "GSDDE": "Ulaştırma",
    "GSDHO": "Ulaştırma",
    "GSRAY": "Spor",
    "GUBRF": "Kimya ve Plastik",
    "GUNDG": "Gıda ve İçecek",
    "GWIND": "Enerji Üretim ve Dağıtım",
    "GZNMI": "Turizm",
    "HALKB": "Bankacılık",
    "HATEK": "Tekstil, Giyim ve Deri",
    "HATSN": "İmalat",
    "HDFGS": "Girişim Sermayesi Yat. Ort.",
    "HEDEF": "Holding",
    "HEKTS": "Kimya ve Plastik",
    "HKTM": "Metal Eşya ve Makine",
    "HLGYO": "Gayrimenkul",
    "HOROZ": "Ulaştırma",
    "HRKET": "Destek ve Hizmet",
    "HTTBT": "Bilişim ve Yazılım",
    "HUBVC": "Girişim Sermayesi Yat. Ort.",
    "HUNER": "Enerji Üretim ve Dağıtım",
    "HURGZ": "Kağıt ve Kağıt Ürünleri",
    "ICBCT": "Bankacılık",
    "ICUGS": "Girişim Sermayesi Yat. Ort.",
    "IDGYO": "Gayrimenkul",
    "IEYHO": "Holding",
    "IHAAS": "Haberleşme",
    "IHEVA": "Dayanıklı Tüketim Ürünleri",
    "IHGZT": "Kağıt ve Kağıt Ürünleri",
    "IHLAS": "Holding",
    "IHLGM": "Gayrimenkul",
    "IHYAY": "Holding",
    "IMASM": "Metal Eşya ve Makine",
    "INDES": "Teknolojik Ürün Ticareti",
    "INFO": "Aracı Kurum",
    "INGRM": "Teknolojik Ürün Ticareti",
    "INTEK": "Bilişim ve Yazılım",
    "INTEM": "Toptan ve Perakende Ticaret",
    "INVEO": "Holding",
    "INVES": "Holding",
    "IPEKE": "Madencilik ve Taş Ocakçılığı",
    "ISATR": "Bankacılık",
    "ISBIR": "Holding",
    "ISBTR": "Bankacılık",
    "ISCTR": "Bankacılık",
    "ISDMR": "Ana Metal",
    "ISFIN": "Finansal Kiralama",
    "ISGSY": "Girişim Sermayesi Yat. Ort.",
    "ISGYO": "Gayrimenkul",
    "ISKPL": "Kimya ve Plastik",
    "ISKUR": "Bankacılık",
    "ISMEN": "Aracı Kurum",
    "ISSEN": "Kimya ve Plastik",
    "ISVEA": "Cam, Seramik, Porselen",
    "ISYAT": "Menkul Kıymet Yat. Ort.",
    "IZENR": "Enerji Üretim ve Dağıtım",
    "IZFAS": "Kimya ve Plastik",
    "IZINV": "Holding",
    "IZMDC": "Ana Metal",
    "JANTS": "Otomotiv Yan Sanayi",
    "KAPLM": "Ambalaj",
    "KARCL": "Ana Metal",
    "KAREL": "Haberleşme",
    "KARSN": "Otomotiv",
    "KARTN": "Ambalaj",
    "KATMR": "Metal Eşya ve Makine",
    "KAYSE": "Gıda ve İçecek",
    "KBORU": "Ana Metal",
    "KCAER": "Ana Metal",
    "KCHOL": "Holding",
    "KENT": "Gıda ve İçecek",
    "KERVN": "Holding",
    "KFEIN": "Bilişim ve Yazılım",
    "KGYO": "Gayrimenkul",
    "KIMMR": "Gıda Perakendeciliği",
    "KLGYO": "Gayrimenkul",
    "KLKIM": "Kimya ve Plastik",
    "KLMSN": "Dayanıklı Tüketim Ürünleri",
    "KLNMA": "Bankacılık",
    "KLRHO": "Holding",
    "KLSER": "Cam, Seramik, Porselen",
    "KLSYN": "Mobilya ve Dekorasyon",
    "KLYPV": "Enerji Teknolojileri",
    "KMPUR": "Kimya ve Plastik",
    "KNFRT": "Gıda ve İçecek",
    "KOCMT": "Ana Metal",
    "KONKA": "Kağıt ve Kağıt Ürünleri",
    "KONTR": "Enerji Teknolojileri",
    "KONYA": "Taş, Toprak, Çimento",
    "KOPOL": "Kimya ve Plastik",
    "KORDS": "Kimya ve Plastik",
    "KOTON": "Giyim, Tekstil ve Deri Ürünleri Perakendeciliği",
    "KOZAA": "Madencilik ve Taş Ocakçılığı",
    "KOZAL": "Madencilik ve Taş Ocakçılığı",
    "KRDMA": "Ana Metal",
    "KRDMB": "Ana Metal",
    "KRDMD": "Ana Metal",
    "KRGYO": "Gayrimenkul",
    "KRONT": "Haberleşme",
    "KRPLS": "Ambalaj",
    "KRSTL": "Gıda ve İçecek",
    "KRTEK": "Tekstil, Giyim ve Deri",
    "KRVGD": "Gıda ve İçecek",
    "KSTUR": "Turizm",
    "KTLEV": "Tasarruf Finansman",
    "KTSKR": "Gıda ve İçecek",
    "KUTPO": "Cam, Seramik, Porselen",
    "KUVVA": "Gıda ve İçecek",
    "KUYAS": "Gayrimenkul",
    "KZBGY": "Gayrimenkul",
    "KZGYO": "Gayrimenkul",
    "LIDER": "Servis Taşımacılığı ve Araç Kiralama",
    "LIDFA": "Faktoring",
    "LILAK": "Kağıt ve Kağıt Ürünleri",
    "LINK": "Bilişim ve Yazılım",
    "LKMNH": "İlaç ve Sağlık",
    "LMKDC": "Taş, Toprak, Çimento",
    "LOGO": "Bilişim ve Yazılım",
    "LRSHO": "Holding",
    "LUKSK": "Tekstil, Giyim ve Deri",
    "LXGYO": "Gayrimenkul",
    "LYDHO": "Toptan ve Perakende Ticaret",
    "LYDYE": "Enerji Üretim ve Dağıtım",
    "MAALT": "Turizm",
    "MACKO": "Destek ve Hizmet",
    "MAGEN": "Enerji Üretim ve Dağıtım",
    "MAKIM": "Metal Eşya ve Makine",
    "MAKTK": "Metal Eşya ve Makine",
    "MANAS": "Enerji Üretim ve Dağıtım",
    "MARBL": "Taş, Toprak, Çimento",
    "MARKA": "Holding",
    "MARMR": "Holding",
    "MARTI": "Turizm",
    "MASFN": "Enerji Teknolojileri",
    "MAVI": "Tekstil, Giyim ve Deri",
    "MCARD": "Destek ve Hizmet",
    "MEDTR": "İlaç ve Sağlık",
    "MEGAP": "Kimya ve Plastik",
    "MEGMT": "Ana Metal",
    "MEKAG": "İmalat",
    "MEPET": "Kimya ve Plastik",
    "MERCN": "Kimya ve Plastik",
    "MERIT": "Turizm",
    "MERKO": "Gıda ve İçecek",
    "METEN": "Enerji Üretim ve Dağıtım",
    "METRO": "Holding",
    "METUR": "Turizm",
    "MEYSU": "Gıda ve İçecek",
    "MGROS": "Gıda Perakendeciliği",
    "MHRGY": "Gayrimenkul",
    "MIATK": "Bilişim ve Yazılım",
    "MMCAS": "Holding",
    "MNDRS": "Tekstil, Giyim ve Deri",
    "MNDTR": "Ambalaj",
    "MOBTL": "Teknolojik Ürün Ticareti",
    "MOGAN": "Enerji Üretim ve Dağıtım",
    "MOPAS": "Gıda Perakendeciliği",
    "MPARK": "İlaç ve Sağlık",
    "MRGYO": "Gayrimenkul",
    "MRSHL": "Kimya ve Plastik",
    "MSGYO": "Gayrimenkul",
    "MTRKS": "Bilişim ve Yazılım",
    "MTRYO": "Menkul Kıymet Yat. Ort.",
    "MZHLD": "Holding",
    "NATEN": "Enerji Üretim ve Dağıtım",
    "NETAS": "Haberleşme",
    "NETCD": "Bilişim ve Yazılım",
    "NIBAS": "Taş, Toprak, Çimento",
    "NTGAZ": "Enerji Üretim ve Dağıtım",
    "NTHOL": "Holding",
    "NUGYO": "Gayrimenkul",
    "NUHCM": "Taş, Toprak, Çimento",
    "OBAMS": "Gıda ve İçecek",
    "OBASE": "Bilişim ve Yazılım",
    "ODAS": "Enerji Üretim ve Dağıtım",
    "ODINE": "Bilişim ve Yazılım",
    "OFSYM": "Gıda ve İçecek",
    "ONCSM": "İlaç ve Sağlık",
    "ONRYT": "Bilişim ve Yazılım",
    "ORCAY": "Gıda ve İçecek",
    "ORGE": "Enerji Teknolojileri",
    "ORMA": "Mobilya ve Dekorasyon",
    "ORZAX": "İlaç ve Sağlık",
    "OSMEN": "Aracı Kurum",
    "OSTIM": "Holding",
    "OTKAR": "Otomotiv",
    "OTTO": "Holding",
    "OYAKC": "Taş, Toprak, Çimento",
    "OYAYO": "Menkul Kıymet Yat. Ort.",
    "OYLUM": "Gıda ve İçecek",
    "OYYAT": "Aracı Kurum",
    "OZATD": "İmalat",
    "OZGYO": "Gayrimenkul",
    "OZKGY": "Gayrimenkul",
    "OZRDN": "Kimya ve Plastik",
    "OZSUB": "Tarım, Hayvancılık, Balıkçılık",
    "OZYSR": "Ana Metal",
    "PAGYO": "Gayrimenkul",
    "PAHOL": "Holding",
    "PAMEL": "Enerji Üretim ve Dağıtım",
    "PAPIL": "Bilişim ve Yazılım",
    "PARSN": "Otomotiv Yan Sanayi",
    "PASEU": "Ulaştırma",
    "PATEK": "Bilişim ve Yazılım",
    "PCILT": "Destek ve Hizmet",
    "PEHOL": "Gayrimenkul",
    "PEKGY": "Gayrimenkul",
    "PENGD": "Gıda ve İçecek",
    "PENTA": "Teknolojik Ürün Ticareti",
    "PETKM": "Kimya ve Plastik",
    "PETUN": "Gıda ve İçecek",
    "PGSUS": "Ulaştırma",
    "PINSU": "Gıda ve İçecek",
    "PKART": "Bilişim ve Yazılım",
    "PKENT": "Turizm",
    "PLTUR": "Servis Taşımacılığı ve Araç Kiralama",
    "PNLSN": "İnşaat",
    "PNSUT": "Gıda ve İçecek",
    "POLHO": "Holding",
    "POLTK": "Ana Metal",
    "PRDGS": "Girişim Sermayesi Yat. Ort.",
    "PRKAB": "Metal Eşya ve Makine",
    "PRKME": "Enerji Üretim ve Dağıtım",
    "PRZMA": "Kağıt ve Kağıt Ürünleri",
    "PSDTC": "Toptan ve Perakende Ticaret",
    "PSGYO": "Gayrimenkul",
    "QNBFK": "Finansal Kiralama",
    "QNBFL": "Finansal Kiralama",
    "QNBTR": "Bankacılık",
    "QUAGR": "Cam, Seramik, Porselen",
    "QUICK": "Sigorta",
    "RALYH": "Holding",
    "RAYSG": "Sigorta",
    "REEDR": "Bilişim ve Yazılım",
    "RGYAS": "Gayrimenkul",
    "RNPOL": "Kimya ve Plastik",
    "RODRG": "Tekstil, Giyim ve Deri",
    "ROYAL": "Tekstil, Giyim ve Deri",
    "RTALB": "İlaç ve Sağlık",
    "RUBNS": "Tekstil, Giyim ve Deri",
    "RUZYE": "Madencilik ve Taş Ocakçılığı",
    "RYGYO": "Gayrimenkul",
    "RYSAS": "Ulaştırma",
    "SAFKR": "Metal Eşya ve Makine",
    "SAHOL": "Holding",
    "SAMAT": "Kağıt ve Kağıt Ürünleri",
    "SANEL": "İnşaat",
    "SANFM": "Kimya ve Plastik",
    "SANKO": "Tekstil, Giyim ve Deri",
    "SARAE": "Enerji Teknolojileri",
    "SARKY": "Ana Metal",
    "SASA": "Kimya ve Plastik",
    "SAYAS": "Enerji Teknolojileri",
    "SDTTR": "Savunma",
    "SEGMN": "Gıda ve İçecek",
    "SEGYO": "Gayrimenkul",
    "SEKFK": "Finansal Kiralama",
    "SEKUR": "Ambalaj",
    "SELEC": "İlaç ve Sağlık",
    "SELGD": "Gıda ve İçecek",
    "SELVA": "Gıda ve İçecek",
    "SERNT": "Cam, Seramik, Porselen",
    "SEYKM": "Kimya ve Plastik",
    "SILVR": "Dayanıklı Tüketim Ürünleri",
    "SISE": "Cam, Seramik, Porselen",
    "SKBNK": "Bankacılık",
    "SKTAS": "Tekstil, Giyim ve Deri",
    "SKYLP": "Bilişim ve Yazılım",
    "SKYMD": "Aracı Kurum",
    "SMART": "Bilişim ve Yazılım",
    "SMRTG": "Enerji Teknolojileri",
    "SMRVA": "Varlık Yönetimi",
    "SNGYO": "Gayrimenkul",
    "SNICA": "Metal Eşya ve Makine",
    "SNKRN": "Destek ve Hizmet",
    "SNPAM": "Tekstil, Giyim ve Deri",
    "SODSN": "Kimya ve Plastik",
    "SOHOE": "Enerji Üretim ve Dağıtım",
    "SOKE": "Gıda ve İçecek",
    "SOKM": "Gıda Perakendeciliği",
    "SONME": "Tekstil, Giyim ve Deri",
    "SRVGY": "Gayrimenkul",
    "SSAAT": "Toptan ve Perakende Ticaret",
    "SUMAS": "Mobilya ve Dekorasyon",
    "SUNTK": "Tekstil, Giyim ve Deri",
    "SURGY": "Gayrimenkul",
    "SUWEN": "Tekstil, Giyim ve Deri",
    "SVGYO": "Gayrimenkul",
    "TABGD": "Gıda ve İçecek",
    "TARKM": "Kimya ve Plastik",
    "TATEN": "Enerji Üretim ve Dağıtım",
    "TATGD": "Gıda ve İçecek",
    "TAVHL": "Ulaştırma",
    "TBORG": "Gıda ve İçecek",
    "TCELL": "Haberleşme",
    "TCKRC": "İmalat",
    "TDGYO": "Gayrimenkul",
    "TEHOL": "Holding",
    "TEKTU": "Turizm",
    "TERA": "Aracı Kurum",
    "TEZOL": "Kağıt ve Kağıt Ürünleri",
    "TGSAS": "Toptan ve Perakende Ticaret",
    "THYAO": "Ulaştırma",
    "TKFEN": "Holding",
    "TKNSA": "Teknolojik Ürün Ticareti",
    "TLMAN": "Ulaştırma",
    "TMPOL": "Kimya ve Plastik",
    "TMSN": "Otomotiv",
    "TNZTP": "İlaç ve Sağlık",
    "TOASO": "Otomotiv",
    "TRALT": "Madencilik ve Taş Ocakçılığı",
    "TRCAS": "Kimya ve Plastik",
    "TRENJ": "Madencilik ve Taş Ocakçılığı",
    "TRGYO": "Gayrimenkul",
    "TRHOL": "Holding",
    "TRILC": "İlaç ve Sağlık",
    "TRMET": "Madencilik ve Taş Ocakçılığı",
    "TSGYO": "Gayrimenkul",
    "TSKB": "Bankacılık",
    "TSPOR": "Spor",
    "TTKOM": "Haberleşme",
    "TTRAK": "Otomotiv",
    "TUCLK": "Ana Metal",
    "TUKAS": "Gıda ve İçecek",
    "TUPRS": "Kimya ve Plastik",
    "TUREX": "Servis Taşımacılığı ve Araç Kiralama",
    "TURGG": "İnşaat",
    "TURSG": "Sigorta",
    "UCAYM": "İnşaat",
    "UFUK": "Holding",
    "ULAS": "Turizm",
    "ULKER": "Gıda ve İçecek",
    "ULUFA": "Faktoring",
    "ULUSE": "Metal Eşya ve Makine",
    "ULUUN": "Gıda ve İçecek",
    "UMPAS": "Holding",
    "UNLU": "Holding",
    "USAK": "Cam, Seramik, Porselen",
    "VAKBN": "Bankacılık",
    "VAKFA": "Faktoring",
    "VAKFN": "Finansal Kiralama",
    "VAKKO": "Tekstil, Giyim ve Deri",
    "VANGD": "Gıda ve İçecek",
    "VBTYZ": "Bilişim ve Yazılım",
    "VERTU": "Girişim Sermayesi Yat. Ort.",
    "VERUS": "Holding",
    "VESBE": "Dayanıklı Tüketim Ürünleri",
    "VESTL": "Dayanıklı Tüketim Ürünleri",
    "VKFYO": "Menkul Kıymet Yat. Ort.",
    "VKGYO": "Gayrimenkul",
    "VKING": "Kağıt ve Kağıt Ürünleri",
    "VRGYO": "Gayrimenkul",
    "VSNMD": "Madencilik ve Taş Ocakçılığı",
    "YAPRK": "Tarım, Hayvancılık, Balıkçılık",
    "YATAS": "Mobilya ve Dekorasyon",
    "YAYLA": "Enerji Üretim ve Dağıtım",
    "YBTAS": "İnşaat",
    "YEOTK": "Enerji Teknolojileri",
    "YESIL": "Holding",
    "YGGYO": "Gayrimenkul",
    "YGYO": "Gayrimenkul",
    "YIGIT": "Otomotiv Yan Sanayi",
    "YKBNK": "Bankacılık",
    "YKSLN": "Ana Metal",
    "YONGA": "Mobilya ve Dekorasyon",
    "YUNSA": "Tekstil, Giyim ve Deri",
    "YYAPI": "İnşaat",
    "YYLGD": "Gıda ve İçecek",
    "ZEDUR": "Enerji Üretim ve Dağıtım",
    "ZERGY": "Gayrimenkul",
    "ZGYO": "Gayrimenkul",
    "ZOREN": "Enerji Üretim ve Dağıtım",
    "ZRGYO": "Gayrimenkul",
}


def fine_sector_for_ticker(ticker: str) -> str | None:
    """Ticker'ın Fintables ince sektör adını döner -- dosyanın "Sektörü
    Tanımsız" listesindeki (11 hisse) veya hiç listede olmayan (yeni IPO
    gibi) ticker'lar için None (Kural 3, `refresh_universe.py`'nin KAP
    yedeğine düşmesi gerektiğinin işareti)."""
    return FINTABLES_TICKER_TO_SEKTOR.get(ticker.strip().upper())


# Kullanıcı raporu (2026-08-13, altıncı tur): "Aracı Kurumlar, Bankalar
# isimli 2 tane boş kopya var" -- KÖK NEDEN: Fintables'ta OLMAYAN 20
# ticker (genelde ikincil/nadir kod, örn. YKB -- YKBNK'nin AYRI bir KAP
# kaydı) `refresh_universe.py::_refresh_bist()`'in KAP YEDEK koluna
# düşüyor, KAP'ın KENDİ ince sektör adını (TÜMÜ BÜYÜK HARF, örn.
# "BANKALAR") HİÇ NORMALLEŞTİRMEDEN `Company.sector`'a yazıyordu --
# Fintables'ın "Bankacılık" (Title Case) etiketiyle STRING olarak HİÇ
# EŞLEŞMEDİĞİ için dashboard'da AYRI (ve çoğu zaman n çok küçük/"boş
# görünen") bir bölüm açılıyordu. Bu sözlük KAP'ın `kap.
# KAP_SEKTOR_TO_UST_SEKTOR` içindeki TÜM ince sektör adlarını (KAP'ın
# KENDİ üst-sektör eşlemesinde ZATEN kataloglı) en yakın Fintables
# karşılığına çevirir -- eşleşme YOKSA (nadir/egzotik bir KAP kategorisi)
# ham KAP adı AYNEN KULLANILIR (Kural 3: uydurma bir Fintables adı
# İCAT EDİLMEZ, sadece KENDİ ayrı bölümünde -- YİNE DE doğru n ile --
# görünür)."""
KAP_INCE_SEKTOR_TO_FINTABLES: dict[str, str] = {
    "BANKALAR": "Bankacılık",
    "ARACI KURUMLAR": "Aracı Kurum",
    "SİGORTA ŞİRKETLERİ": "Sigorta",
    "FİNANSMAN ŞİRKETLERİ": "Tasarruf Finansman",
    "FİNANSAL KİRALAMA VE FAKTORİNG ŞİRKETLERİ": "Finansal Kiralama",
    "VARLIK YÖNETİM ŞİRKETLERİ": "Varlık Yönetimi",
    "MENKUL KIYMET YATIRIM ORTAKLIKLARI": "Menkul Kıymet Yat. Ort.",
    "GİRİŞİM SERMAYESİ YATIRIM ORTAKLIKLARI": "Girişim Sermayesi Yat. Ort.",
    "HOLDİNGLER VE YATIRIM ŞİRKETLERİ": "Holding",
    "GAYRİMENKUL YATIRIM ORTAKLIKLARI": "Gayrimenkul",
    "GAYRİMENKUL FAALİYETLERİ": "Gayrimenkul",
    "TARIM VE HAYVANCILIK AVCILIK VE İLGİLİ HİZMET FAALİYETLERİ": "Tarım, Hayvancılık, Balıkçılık",
    "BALIKÇILIK VE SU ÜRÜNLERİ": "Tarım, Hayvancılık, Balıkçılık",
    "GIDA, İÇECEK VE TÜTÜN": "Gıda ve İçecek",
    "TEKSTİL, GİYİM EŞYASI VE DERİ": "Tekstil, Giyim ve Deri",
    "ORMAN ÜRÜNLERİ VE MOBİLYA": "Mobilya ve Dekorasyon",
    "TELEKOMÜNİKASYON": "Haberleşme",
    "TAŞ VE TOPRAĞA DAYALI": "Taş, Toprak, Çimento",
    "ANA METAL SANAYİ": "Ana Metal",
    "İNŞAAT VE BAYINDIRLIK İŞLERİ": "İnşaat",
    "TOPTAN TİCARET": "Toptan ve Perakende Ticaret",
    "PERAKENDE TİCARET": "Toptan ve Perakende Ticaret",
    "ULAŞTIRMA VE DEPOLAMA": "Ulaştırma",
    "KONAKLAMA": "Turizm",
    "BİLİŞİM": "Bilişim ve Yazılım",
    "İNSAN SAĞLIĞI VE SOSYAL HİZMETLER": "İlaç ve Sağlık",
    "SAVUNMA": "Savunma",
}


def fine_sector_for_kap_label(kap_label: str) -> str:
    """KAP'ın ham (BÜYÜK HARF) ince sektör adını, varsa Fintables'ın
    karşılığına çevirir -- eşleşme YOKSA ham KAP adı AYNEN döner (bkz.
    `KAP_INCE_SEKTOR_TO_FINTABLES` üstü not)."""
    return KAP_INCE_SEKTOR_TO_FINTABLES.get(kap_label, kap_label)
